/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_content_res_AssetManager_AssetInputStream */

#ifndef _Included_android_content_res_AssetManager_AssetInputStream
#define _Included_android_content_res_AssetManager_AssetInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef android_content_res_AssetManager_AssetInputStream_MAX_SKIP_BUFFER_SIZE
#define android_content_res_AssetManager_AssetInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
