/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Canvas_VertexMode */

#ifndef _Included_android_graphics_Canvas_VertexMode
#define _Included_android_graphics_Canvas_VertexMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
